# geek-shelf theme configuration

menu:
  首页: /
  归档: /archives
  CATEGORY: /categories/
  TAG: /tags/

favicon: /favicon.ico

comments:
  enable: true
  provider: utterances
  repo: cardchoosen/blog
  issue_term: pathname
  label: comment
  theme: github-light
  dark_theme: github-dark
